collections:
  posts:
    output: true

permalink: /blog/:title.html

#permalink: pretty
include: ['_pages']

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - [jekyll-paginate]

paginate_path: blog/page:num/

paginate: 6

