theme: jekyll-theme-minimal
collections:
  posts:
    output: true
    permalink: /:title:.html

permalink: pretty
include: ['_pages']

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate